#Personal
author:
  - name: Guillermo Remache
    email: guillermo@justthingsido
    url: https://justthingsido.com


name: Guillermo Remache
email: guillermo@justthingsido.com

development: false ##or FALSE for production

ga: UA-64098106-1
title: JTIDo
# Site settings
description: >
  If there is something i have not done yet, then it is next on my list. If there is something I do not know,
  then that will be the next thing I learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://justthingsido.com" # the base hostname & protocol for your site
twitter_username: GRemache93
github_username:  justthingsido

permalink: pretty

# Build settings
markdown: kramdown
gems:
  # - octopress-minify-html
  - jekyll-feed
  - jekyll-sitemap


highlighter: rouge
encoding: utf-8



exclude: [node_modules, gulpfile.js, package.json, 'assets/css/main.sass']
keywords: >
  wonder,  bookmarks,  news,  yahoo,  hurt,  continue,  google,  heart,  masochist,  reading,  mind,  morning,
  person,  body,  eyes,  feel,  night,  sleep,  world
